plugins:
  directoryopus_enabled:
    default: false
    client: true
  directoryopus_current_version:
    default: 12
    client: true
  directoryopus_account_link_url:
    default: ""
    client: false
  directoryopus_account_link_code_code:
    default: ""
    client: false
  directoryopus_account_link_code_name:
    default: ""
    client: false
  directoryopus_composer_help_title:
    default: ""
    client: true
  directoryopus_composer_help_url:
    default: ""
    client: true
  directoryopus_refresh_job_test_mode:
    default: true
    client: false
